### ISSUE TITLE
From Tiru: define how this format could be used to re-publish evidence claims in a certificate

### ISSUE THREAD

**Issue by ounsworth** [EntrustCorporation/draft-rats-pkix-evidence#2]
While the primary goal of this draft is to convey attestation data from an HSM to a CA, Tiru points out that it could also be used to put evidence claims into a published certificate.

The obvious way to do that would be to add a section to this draft that defines

```
ext-evidenceClaims EXTENSION ::= {
  SYNTAX claims SET SIZE (1..MAX) OF EVIDENCE-CLAIM
  IDENTIFIED BY TBD
}
```
which is basically an un-signed version of our evidence claims set as an X.509v3 extension.

This would also need a pretty robust Privacy Considerations section suggesting, for example, that CAs should include in their cert profile a list of evidence claim (identified by OID) which MAY be copied from CSR to cert, and any other claims MUST NOT be copied.

**Comment by tireddy2** [comment]
Raised a PR https://github.com/EntrustCorporation/draft-rats-pkix-evidence/pull/3

**Comment by ounsworth** [comment]
PR has been merged. Hence closing this ticket.
